# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import origin_pb2 as origin__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in origin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OriginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ingest_video_rpc = channel.stream_stream(
                '/origin.Origin/ingest_video_rpc',
                request_serializer=origin__pb2.ingest_video_request.SerializeToString,
                response_deserializer=origin__pb2.ingest_video_response.FromString,
                _registered_method=True)
        self.fetch_chunk_rpc = channel.stream_stream(
                '/origin.Origin/fetch_chunk_rpc',
                request_serializer=origin__pb2.fetch_chunk_request.SerializeToString,
                response_deserializer=origin__pb2.fetch_chunk_response.FromString,
                _registered_method=True)


class OriginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ingest_video_rpc(self, request_iterator, context):
        """PoP to Origin RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fetch_chunk_rpc(self, request_iterator, context):
        """Origin to PoP RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OriginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ingest_video_rpc': grpc.stream_stream_rpc_method_handler(
                    servicer.ingest_video_rpc,
                    request_deserializer=origin__pb2.ingest_video_request.FromString,
                    response_serializer=origin__pb2.ingest_video_response.SerializeToString,
            ),
            'fetch_chunk_rpc': grpc.stream_stream_rpc_method_handler(
                    servicer.fetch_chunk_rpc,
                    request_deserializer=origin__pb2.fetch_chunk_request.FromString,
                    response_serializer=origin__pb2.fetch_chunk_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'origin.Origin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('origin.Origin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Origin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ingest_video_rpc(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/origin.Origin/ingest_video_rpc',
            origin__pb2.ingest_video_request.SerializeToString,
            origin__pb2.ingest_video_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def fetch_chunk_rpc(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/origin.Origin/fetch_chunk_rpc',
            origin__pb2.fetch_chunk_request.SerializeToString,
            origin__pb2.fetch_chunk_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
