# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: origin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'origin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corigin.proto\x12\x06origin\"\xf5\x02\n\x14ingest_video_request\x12\x13\n\x0bstreamer_id\x18\x01 \x01(\x05\x12$\n\x0cvideo_format\x18\x02 \x01(\x0e\x32\x0e.origin.Format\x12\'\n\x0bvideo_codec\x18\x03 \x01(\x0e\x32\x12.origin.VideoCodec\x12\'\n\x0b\x61udio_codec\x18\x04 \x01(\x0e\x32\x12.origin.AudioCodec\x12\x12\n\nvideo_data\x18\x05 \x01(\x0c\x12\x1c\n\x14\x65nable_ml_censorship\x18\x06 \x01(\x08\x12\x18\n\x10\x65nable_watermark\x18\x07 \x01(\x08\x12%\n\tvideo_res\x18\x08 \x01(\x0e\x32\x12.origin.Resolution\x12%\n\nframe_rate\x18\t \x01(\x0e\x32\x11.origin.FrameRate\x12\x1a\n\x12video_bitrate_mbps\x18\n \x01(\x05\x12\x1a\n\x12\x61udio_bitrate_kbps\x18\x0b \x01(\x05\"7\n\x15ingest_video_response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"<\n\x13\x66\x65tch_chunk_request\x12\x13\n\x0bstreamer_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\x05\"J\n\x14\x66\x65tch_chunk_response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x12\n\nchunk_data\x18\x03 \x01(\x0c*;\n\nVideoCodec\x12\x08\n\x04H264\x10\x00\x12\x08\n\x04H265\x10\x01\x12\x07\n\x03VP8\x10\x02\x12\x07\n\x03VP9\x10\x03\x12\x07\n\x03\x41V1\x10\x04*\x1e\n\nAudioCodec\x12\x07\n\x03\x41\x41\x43\x10\x00\x12\x07\n\x03MP3\x10\x01*?\n\nResolution\x12\t\n\x05p1080\x10\x00\x12\x08\n\x04p720\x10\x01\x12\x08\n\x04p480\x10\x02\x12\x08\n\x04p360\x10\x03\x12\x08\n\x04p240\x10\x04*!\n\tFrameRate\x12\t\n\x05\x66ps30\x10\x00\x12\t\n\x05\x66ps60\x10\x01*\x1a\n\x06\x46ormat\x12\x07\n\x03MP4\x10\x00\x12\x07\n\x03HLS\x10\x01\x32\xb3\x01\n\x06Origin\x12U\n\x10ingest_video_rpc\x12\x1c.origin.ingest_video_request\x1a\x1d.origin.ingest_video_response\"\x00(\x01\x30\x01\x12R\n\x0f\x66\x65tch_chunk_rpc\x12\x1b.origin.fetch_chunk_request\x1a\x1c.origin.fetch_chunk_response\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'origin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOCODEC']._serialized_start=595
  _globals['_VIDEOCODEC']._serialized_end=654
  _globals['_AUDIOCODEC']._serialized_start=656
  _globals['_AUDIOCODEC']._serialized_end=686
  _globals['_RESOLUTION']._serialized_start=688
  _globals['_RESOLUTION']._serialized_end=751
  _globals['_FRAMERATE']._serialized_start=753
  _globals['_FRAMERATE']._serialized_end=786
  _globals['_FORMAT']._serialized_start=788
  _globals['_FORMAT']._serialized_end=814
  _globals['_INGEST_VIDEO_REQUEST']._serialized_start=25
  _globals['_INGEST_VIDEO_REQUEST']._serialized_end=398
  _globals['_INGEST_VIDEO_RESPONSE']._serialized_start=400
  _globals['_INGEST_VIDEO_RESPONSE']._serialized_end=455
  _globals['_FETCH_CHUNK_REQUEST']._serialized_start=457
  _globals['_FETCH_CHUNK_REQUEST']._serialized_end=517
  _globals['_FETCH_CHUNK_RESPONSE']._serialized_start=519
  _globals['_FETCH_CHUNK_RESPONSE']._serialized_end=593
  _globals['_ORIGIN']._serialized_start=817
  _globals['_ORIGIN']._serialized_end=996
# @@protoc_insertion_point(module_scope)
