# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: origin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'origin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corigin.proto\x12\x06origin\"\xf5\x01\n\x14ingest_video_request\x12\x13\n\x0bstreamer_id\x18\x01 \x01(\x05\x12$\n\x0cvideo_format\x18\x02 \x01(\x0e\x32\x0e.origin.Format\x12\"\n\x0bvideo_codec\x18\x03 \x01(\x0e\x32\r.origin.Codec\x12\x12\n\nvideo_data\x18\x04 \x01(\x0c\x12\x1c\n\x14\x65nable_ml_censorship\x18\x05 \x01(\x08\x12%\n\tvideo_res\x18\x06 \x01(\x0e\x32\x12.origin.Resolution\x12%\n\nframe_rate\x18\x07 \x01(\x0e\x32\x11.origin.FrameRate\"(\n\x15ingest_video_response\x12\x0f\n\x07success\x18\x01 \x01(\x08*@\n\x05\x43odec\x12\x08\n\x04H264\x10\x00\x12\x08\n\x04H265\x10\x01\x12\x08\n\x04H266\x10\x02\x12\x07\n\x03VP8\x10\x03\x12\x07\n\x03VP9\x10\x04\x12\x07\n\x03\x41V1\x10\x05*?\n\nResolution\x12\t\n\x05p1080\x10\x00\x12\x08\n\x04p720\x10\x01\x12\x08\n\x04p480\x10\x02\x12\x08\n\x04p360\x10\x03\x12\x08\n\x04p240\x10\x04*!\n\tFrameRate\x12\t\n\x05\x66ps30\x10\x00\x12\t\n\x05\x66ps60\x10\x01*\x1a\n\x06\x46ormat\x12\x07\n\x03MP4\x10\x00\x12\x07\n\x03HPS\x10\x01\x32_\n\x06Origin\x12U\n\x10ingest_video_rpc\x12\x1c.origin.ingest_video_request\x1a\x1d.origin.ingest_video_response\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'origin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODEC']._serialized_start=314
  _globals['_CODEC']._serialized_end=378
  _globals['_RESOLUTION']._serialized_start=380
  _globals['_RESOLUTION']._serialized_end=443
  _globals['_FRAMERATE']._serialized_start=445
  _globals['_FRAMERATE']._serialized_end=478
  _globals['_FORMAT']._serialized_start=480
  _globals['_FORMAT']._serialized_end=506
  _globals['_INGEST_VIDEO_REQUEST']._serialized_start=25
  _globals['_INGEST_VIDEO_REQUEST']._serialized_end=270
  _globals['_INGEST_VIDEO_RESPONSE']._serialized_start=272
  _globals['_INGEST_VIDEO_RESPONSE']._serialized_end=312
  _globals['_ORIGIN']._serialized_start=508
  _globals['_ORIGIN']._serialized_end=603
# @@protoc_insertion_point(module_scope)
